import{scenarios}from'./scenarios.mjs';import{stateAt,reduce,initialState}from'./core.mjs';
const $=id=>document.getElementById(id);let scenarioIndex=0,eventIndex=0,autoTimer=null;
const scenarioEl=$('scenario'),timeline=$('timeline');
for(const[sIndex,s]of scenarios.entries()){const option=document.createElement('option');option.value=sIndex;option.textContent=s.name;scenarioEl.append(option)}
function render(){
 const scenario=scenarios[scenarioIndex],state=stateAt(scenario,eventIndex),event=scenario.events[eventIndex],task=state.pending||state.task||scenario.events[0].task;
 timeline.replaceChildren(...scenario.events.map((e,i)=>{const li=document.createElement('li');li.dataset.step=i+1;li.className=i===eventIndex?'active':i<eventIndex?'done':'';li.innerHTML=`<small>${e.time} · ${e.speaker}</small>${e.spoken}`;li.onclick=()=>{eventIndex=i;render()};return li}));
 const active=timeline.children[eventIndex];active?.scrollIntoView({block:'nearest'});
 $('event-counter').textContent=`Event ${eventIndex+1} of ${scenario.events.length}`;$('prev').disabled=eventIndex===0;$('next').disabled=eventIndex===scenario.events.length-1;
 $('task-title').textContent=task.title;$('task-owner').textContent=task.owner;$('task-due').textContent=task.due;$('task-dependency').textContent=task.dependency;$('task-alarm').textContent=task.alarm||'None';
 $('task-status').textContent=task.status[0].toUpperCase()+task.status.slice(1);$('task-status').className=`status ${task.status}`;$('confidence').textContent=`Confidence ${Math.round(state.confidence*100)}%`;
 const card=$('change-card');if(state.change){card.classList.remove('hidden');if(state.change.type==='question')$('change-copy').innerHTML=`<p>${state.change.question}</p>`;else $('change-copy').innerHTML=`<p><span class="before">${state.change.before||'New commitment'}</span><br><span class="after">→ ${state.change.after||state.change.label}</span></p>`}else card.classList.add('hidden');
 $('impact-title').textContent=state.message;$('impact-copy').textContent=state.writes?`${state.writes} approved Bee write${state.writes===1?'':'s'} · ${state.sources.length} linked source${state.sources.length===1?'':'s'}`:'Nothing is written until you approve.';
}
scenarioEl.onchange=()=>{scenarioIndex=Number(scenarioEl.value);eventIndex=0;render()};$('prev').onclick=()=>{eventIndex=Math.max(0,eventIndex-1);render()};$('next').onclick=()=>{eventIndex=Math.min(scenarios[scenarioIndex].events.length-1,eventIndex+1);render()};$('approve').onclick=()=>{const scenario=scenarios[scenarioIndex];if(scenario.events[eventIndex+1]?.kind==='approve')eventIndex++;render()};$('dismiss').onclick=()=>{$('change-card').classList.add('hidden');$('impact-title').textContent='Current plan preserved';$('impact-copy').textContent='BeeLoop made no downstream change.'};
$('run-demo').onclick=()=>{clearInterval(autoTimer);scenarioIndex=0;scenarioEl.value='0';eventIndex=0;render();autoTimer=setInterval(()=>{if(eventIndex>=scenarios[0].events.length-1){clearInterval(autoTimer);return}eventIndex++;render()},4200)};
$('connect-live').onclick=async()=>{const button=$('connect-live');button.textContent='Checking local Bee CLI…';try{const response=await fetch('/api/status');const status=await response.json();if(!status.authenticated)throw new Error(status.message||'Bee CLI is not authenticated');$('source-label').textContent=`Live Bee CLI · ${status.profile||'authenticated'}`;$('source-pill').classList.add('live');$('mode-badge').textContent='LIVE BEE';$('footer-mode').textContent='Live processed Bee events are streamed from the authenticated local CLI.';button.textContent='Connected';const events=new EventSource('/api/bee/stream');events.onmessage=e=>console.log('Bee event',JSON.parse(e.data))}catch(error){$('impact-title').textContent='Live Bee connection needs setup';$('impact-copy').textContent=error.message;button.textContent='Connect to local Bee CLI'}};
render();
