import{createServer}from'node:http';import{readFile,stat}from'node:fs/promises';import{extname,join,normalize}from'node:path';import{fileURLToPath}from'node:url';
const root=fileURLToPath(new URL('.',import.meta.url));const port=Number(process.env.PORT||4173);let beeClient=null,beeError=null;
async function loadBee(){try{const{createBeeClient}=await import('@beeai/cli/lib');beeClient=createBeeClient();return beeClient}catch(error){beeError=error;return null}}
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.png':'image/png','.svg':'image/svg+xml'};
async function json(res,status,data){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(data))}
async function handler(req,res){
 if(req.url==='/api/status'){const bee=beeClient||await loadBee();if(!bee)return json(res,200,{authenticated:false,mode:'synthetic',message:'Install @beeai/cli, run bee login, then restart BeeLoop.'});try{const profile=await bee.api.me();return json(res,200,{authenticated:true,mode:'live',profile:profile?.email||profile?.name||'Bee account'})}catch(error){return json(res,200,{authenticated:false,mode:'synthetic',message:'Bee CLI is installed but not authenticated. Run bee login.'})}}
 if(req.url==='/api/bee/stream'){const bee=beeClient||await loadBee();if(!bee)return json(res,503,{error:'Bee CLI unavailable'});res.writeHead(200,{'content-type':'text/event-stream','cache-control':'no-cache','connection':'keep-alive'});try{const stream=bee.sse.streamJson({types:['new-utterance','todo-created','todo-updated','todo-deleted']});for await(const event of stream.events){res.write(`data: ${JSON.stringify(event)}\n\n`);if(res.destroyed)break}}catch(error){res.write(`event: error\ndata: ${JSON.stringify({message:error.message})}\n\n`)}return}
 const requested=req.url==='/'?'index.html':decodeURIComponent(req.url.split('?')[0].slice(1));const safe=normalize(requested).replace(/^(\.\.[/\\])+/,''),path=join(root,safe);if(!path.startsWith(root))return json(res,403,{error:'Forbidden'});try{if(!(await stat(path)).isFile())throw new Error('not file');const body=await readFile(path);res.writeHead(200,{'content-type':mime[extname(path)]||'application/octet-stream','cache-control':'no-store'});res.end(body)}catch{json(res,404,{error:'Not found'})}
}
createServer(handler).listen(port,'127.0.0.1',()=>console.log(`BeeLoop running at http://127.0.0.1:${port}`));
